<?php

require_once dirname(__FILE__).'/../../Sqlite/Table.php';

/**
 * Test class for Joiner_Sqlite_Table.
 * Generated by PHPUnit on 2011-03-11 at 17:22:15.
 */
class Joiner_Sqlite_TableTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Joiner_Sqlite_Table
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Joiner_Sqlite_Table;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testToSqlUpdate().
     */
    public function testToSqlUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testToSqlDelete().
     */
    public function testToSqlDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetMetas().
     */
    public function testGetMetas() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
