<?php

require_once dirname(__FILE__).'/../../Sqlite/Adapter.php';

/**
 * Test class for Joiner_Sqlite_Adapter.
 * Generated by PHPUnit on 2011-03-11 at 17:41:43.
 */
class Joiner_Sqlite_AdapterTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Joiner_Sqlite_Adapter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Joiner_Sqlite_Adapter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testGetTable().
     */
    public function testGetTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
