<?php

require_once dirname(__FILE__).'/../ZendPaginatorAdapter.php';

/**
 * Test class for Joiner_ZendPaginatorAdapter.
 * Generated by PHPUnit on 2011-03-11 at 17:19:57.
 */
class Joiner_ZendPaginatorAdapterTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Joiner_ZendPaginatorAdapter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Joiner_ZendPaginatorAdapter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testCount().
     */
    public function testCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetItems().
     */
    public function testGetItems() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
