<?php

require_once dirname(__FILE__).'/../Expression.php';

/**
 * Test class for Joiner_Expression.
 * Generated by PHPUnit on 2011-03-08 at 23:51:56.
 */
class Joiner_ExpressionTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Joiner_Expression
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Joiner_Expression('md5(?)', array('p4ssword'));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @todo Implement test__toString().
	 */
	public function test__toString() {
		$this->assertEquals('md5(?)', $this->object->__toString());
		$this->assertEquals(array('p4ssword'), $this->object->params);
	}
}
?>
