<?php

require_once dirname(__FILE__).'/../Joiner.php';

/**
 * Test class for Joiner.
 * Generated by PHPUnit on 2011-03-08 at 23:08:36.
 */
class JoinerTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Joiner_Adapter
	 */
	protected $adapter1;

	/**
	 * @var Joiner_Adapter
	 */
	protected $adapter2;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->adapter1 = Joiner::setAdapter('test', 'sqlite::memory:');
		$this->adapter2 = Joiner::setAdapter('test2', 'sqlite::memory:');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	public function testSetAdapter() {
		$this->assertEquals(true, $this->adapter1 instanceof Joiner_Adapter);
		$this->assertEquals(true, get_class(Joiner::setAdapter('none', 'foo::bar:')) === 'Joiner_Adapter');
		$this->assertEquals(true, get_class($this->adapter1) === 'Joiner_Sqlite_Adapter');
	}

	public function testSetCurrentAdapter() {
		Joiner::setCurrentAdapter('test2');
	}

	/**
	 * @todo Implement testGetAdapter().
	 * @depends testSetCurrentAdapter
	 */
	public function testGetAdapter() {


		$this->assertEquals(true, Joiner::getAdapter() === $this->adapter2);

		$this->assertEquals(true, Joiner::getAdapter() instanceof Joiner_Adapter);
		$this->assertEquals(true, Joiner::getAdapter('test') instanceof Joiner_Adapter);
		$this->assertEquals(true, Joiner::getAdapter('test2') instanceof Joiner_Adapter);
		$this->assertEquals(true, $this->adapter1 !== $this->adapter2);
		$this->assertEquals(true, Joiner::getAdapter('test') === $this->adapter1);
		$this->assertEquals(true, Joiner::getAdapter('test2') === $this->adapter2);
		$this->setExpectedException('Exception');
		Joiner::getAdapter('foobar');

	}
}
?>
