<?php

require_once dirname(__FILE__).'/../PDOLogger.php';
require_once dirname(__FILE__).'/../Joiner.php';

/**
 * Test class for Joiner_PDOLogger.
 * Generated by PHPUnit on 2011-03-10 at 21:56:42.
 */
class Joiner_PDOLoggerTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Joiner_PDOLogger
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		// Just to init Joiner and to set internally the path
		Joiner::setAdapter('test', 'sqlite::memory:');
		
		$this->object = new Joiner_PDOLogger(new PDO('sqlite::memory:'));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	public function testGetPdo() {
		$this->assertEquals(true, $this->object->getPdo() instanceof PDO);
	}

	public function test__call() {
		$this->assertEquals("'bar'", $this->object->quote('bar'));
	}

	/**
	 * @depends test__call
	 */
	public function testToArray() {
		$array = $this->object->toArray();
		$this->assertEquals(1, count($array));
		$this->assertEquals(3, count($array[0]));
		$this->assertEquals('PDO::quote', $array[0][0]);
		$this->assertEquals('bar', $array[0][1][0]);
		$this->assertEquals(true, is_numeric($array[0][2]));
	}

	/**
	 * @depends test__call
	 */
	public function test__toString() {
		$aspected = "<table border=1><tr><th>Func<th>Args<th>Milliseconds<tr><td>PDO::quote<td>Array\n(\n    [0] => bar\n)\n<td>0<tr><th colspan=2>Milliseconds:<td>0</table>";
		$this->assertEquals($aspected, $this->object->__toString());
	}


	/**
	 * @depends test__call
	 */
	public function test__call_2() {
		$this->assertEquals(true,
				$this->object->query('select 1') instanceof Joiner_PDOStatementLogger
			);
	}

}
?>
