<?php

require_once dirname(__FILE__).'/../Joiner.php';
require_once dirname(__FILE__).'/../Adapter.php';

/**
 * Test class for Joiner_Adapter.
 * Generated by PHPUnit on 2011-03-08 at 23:08:36.
 */
class Joiner_AdapterTest extends PHPUnit_Framework_TestCase {

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

}
?>
